---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/9/posts/36/comments":
    get:
      summary: Retrieves a comment
      tags:
      - Blogs
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  author_id:
                    type: integer
                  post_id:
                    type: integer
                  text:
                    type: integer
                required:
                - id
                - author_id
                - post_id
                - text
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  author_id:
                    type: integer
                  post_id:
                    type: integer
                  text:
                    type: integer
                required:
                - id
                - author_id
                - post_id
                - text
        '404':
          description: blog not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
